/* Process model C form file: pm_source_web.pr.c */
/* Portions of this file copyright 1986-2012 by OPNET Technologies, Inc. */


/*
 =========================== NOTE ==========================
 This file is automatically generated from pm_source_web.pr.m
 during a process model compilation.

 Do NOT manually edit this file.
 Manual edits will be lost during the next compilation.
 =========================== NOTE ==========================
*/



/* This variable carries the header into the object file */
const char pm_source_web_pr_c [] = "MIL_3_Tfile_Hdr_ 171A 30A modeler 7 5533AE0C 5533AE0C 1 FTNK-B0013 s146147 0 0 none none 0 0 none 0 0 0 0 0 0 0 0 2b74 2                                                                                                                                                                                                                                                                                                                                                                                                       ";
#include <string.h>



/* OPNET system definitions */
#include <opnet.h>



/* Header Block */

/* Macros */
#define PowerUp (op_intrpt_type() == OPC_INTRPT_BEGSIM)
#define	PckGen	(intrpt_code == SSC_GENERATE)

/* Interrupt code values.			*/
#define		SSC_GENERATE			0


/* Node configuration constants.	*/
#define		SSC_STRM_TO_LOW			0


/* End of Header Block */

#if !defined (VOSD_NO_FIN)
#undef	BIN
#undef	BOUT
#define	BIN		FIN_LOCAL_FIELD(_op_last_line_passed) = __LINE__ - _op_block_origin;
#define	BOUT	BIN
#define	BINIT	FIN_LOCAL_FIELD(_op_last_line_passed) = 0; _op_block_origin = __LINE__;
#else
#define	BINIT
#endif /* #if !defined (VOSD_NO_FIN) */



/* State variable definitions */
typedef struct
	{
	/* Internal state tracking for FSM */
	FSM_SYS_STATE
	/* State Variables */
	Objid	                  		own_id                                          ;
	Stathandle	             		requests_sent_hndl                              ;
	double	                 		req_rate                                        ;
	double	                 		requests_sent                                   ;
	} pm_source_web_state;

#define own_id                  		op_sv_ptr->own_id
#define requests_sent_hndl      		op_sv_ptr->requests_sent_hndl
#define req_rate                		op_sv_ptr->req_rate
#define requests_sent           		op_sv_ptr->requests_sent

/* These macro definitions will define a local variable called	*/
/* "op_sv_ptr" in each function containing a FIN statement.	*/
/* This variable points to the state variable data structure,	*/
/* and can be used from a C debugger to display their values.	*/
#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE
#define FIN_PREAMBLE_DEC	pm_source_web_state *op_sv_ptr;
#define FIN_PREAMBLE_CODE	\
		op_sv_ptr = ((pm_source_web_state *)(OP_SIM_CONTEXT_PTR->_op_mod_state_ptr));


/* No Function Block */

#if !defined (VOSD_NO_FIN)
enum { _op_block_origin = __LINE__ };
#endif

/* Undefine optional tracing in FIN/FOUT/FRET */
/* The FSM has its own tracing code and the other */
/* functions should not have any tracing.		  */
#undef FIN_TRACING
#define FIN_TRACING

#undef FOUTRET_TRACING
#define FOUTRET_TRACING

#if defined (__cplusplus)
extern "C" {
#endif
	void pm_source_web (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Obtype _op_pm_source_web_init (int * init_block_ptr);
	void _op_pm_source_web_diag (OP_SIM_CONTEXT_ARG_OPT);
	void _op_pm_source_web_terminate (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Address _op_pm_source_web_alloc (VosT_Obtype, int);
	void _op_pm_source_web_svar (void *, const char *, void **);


#if defined (__cplusplus)
} /* end of 'extern "C"' */
#endif




/* Process model interrupt handling procedure */


void
pm_source_web (OP_SIM_CONTEXT_ARG_OPT)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	FIN_MT (pm_source_web ());

		{
		/* Temporary Variables */
		/* Variables used in state transitions.		*/
		int			intrpt_code;
		/* End of Temporary Variables */


		FSM_ENTER_NO_VARS ("pm_source_web")

		FSM_BLOCK_SWITCH
			{
			/*---------------------------------------------------------*/
			/** state (INIT) enter executives **/
			FSM_STATE_ENTER_FORCED_NOLABEL (0, "INIT", "pm_source_web [INIT enter execs]")
				FSM_PROFILE_SECTION_IN ("pm_source_web [INIT enter execs]", state0_enter_exec)
				{
				/* Generation.											*/
				
				/* Obtain the object id of the surrounding module.					*/
				own_id = op_id_self (); //state variable
				
				/* Read the values of the packet generation parameters	*/
				op_ima_obj_attr_get (own_id, "ReqRate", &req_rate);
				
				/* Register the statistics that will be maintained by this model.	*/
				
				requests_sent_hndl   = op_stat_reg ("Generator.Requests Sent (packets)",		OPC_STAT_INDEX_NONE, OPC_STAT_LOCAL);
				
				}
				FSM_PROFILE_SECTION_OUT (state0_enter_exec)

			/** state (INIT) exit executives **/
			FSM_STATE_EXIT_FORCED (0, "INIT", "pm_source_web [INIT exit execs]")
				FSM_PROFILE_SECTION_IN ("pm_source_web [INIT exit execs]", state0_exit_exec)
				{
				requests_sent=0;
				}
				FSM_PROFILE_SECTION_OUT (state0_exit_exec)


			/** state (INIT) transition processing **/
			FSM_TRANSIT_ONLY ((PowerUp), 1, state1_enter_exec, ;, INIT, "PowerUp", "", "INIT", "GENERATE", "tr_0", "pm_source_web [INIT -> GENERATE : PowerUp / ]")
				/*---------------------------------------------------------*/



			/** state (GENERATE) enter executives **/
			FSM_STATE_ENTER_UNFORCED (1, "GENERATE", state1_enter_exec, "pm_source_web [GENERATE enter execs]")
				FSM_PROFILE_SECTION_IN ("pm_source_web [GENERATE enter execs]", state1_enter_exec)
				{
				/*Interupt for generation*/
				if (req_rate <0)
					{
					req_rate = 15.0;
					}
				
				op_intrpt_schedule_self(op_sim_time() + op_dist_exponential(req_rate), SSC_GENERATE);
				}
				FSM_PROFILE_SECTION_OUT (state1_enter_exec)

			/** blocking after enter executives of unforced state. **/
			FSM_EXIT (3,"pm_source_web")


			/** state (GENERATE) exit executives **/
			FSM_STATE_EXIT_UNFORCED (1, "GENERATE", "pm_source_web [GENERATE exit execs]")
				FSM_PROFILE_SECTION_IN ("pm_source_web [GENERATE exit execs]", state1_exit_exec)
				{
				/* Create a packet with the specified format.	*/
				Packet				*pkptr;
				int pck_size;
				do
					{
					pck_size= op_dist_exponential(600);
					}while(pck_size>1400 || pck_size<300);
				pkptr = op_pk_create (pck_size*8);
				//printf("\n NODE %d generated WEB GET packet", op_id_self ());
				
				op_pk_send (pkptr, SSC_STRM_TO_LOW);
				op_stat_write (requests_sent_hndl, requests_sent=requests_sent + 1.0);
				
				/* Determine the code of the interrupt, which is used in evaluating	*/
				/* state transition conditions.										*/
				intrpt_code = op_intrpt_code ();
				
				}
				FSM_PROFILE_SECTION_OUT (state1_exit_exec)


			/** state (GENERATE) transition processing **/
			FSM_TRANSIT_ONLY ((PckGen), 1, state1_enter_exec, ;, GENERATE, "PckGen", "", "GENERATE", "GENERATE", "tr_1", "pm_source_web [GENERATE -> GENERATE : PckGen / ]")
				/*---------------------------------------------------------*/



			}


		FSM_EXIT (0,"pm_source_web")
		}
	}




void
_op_pm_source_web_diag (OP_SIM_CONTEXT_ARG_OPT)
	{
	/* No Diagnostic Block */
	}




void
_op_pm_source_web_terminate (OP_SIM_CONTEXT_ARG_OPT)
	{

	FIN_MT (_op_pm_source_web_terminate ())


	/* No Termination Block */

	Vos_Poolmem_Dealloc (op_sv_ptr);

	FOUT
	}


/* Undefine shortcuts to state variables to avoid */
/* syntax error in direct access to fields of */
/* local variable prs_ptr in _op_pm_source_web_svar function. */
#undef own_id
#undef requests_sent_hndl
#undef req_rate
#undef requests_sent

#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE

#define FIN_PREAMBLE_DEC
#define FIN_PREAMBLE_CODE

VosT_Obtype
_op_pm_source_web_init (int * init_block_ptr)
	{
	VosT_Obtype obtype = OPC_NIL;
	FIN_MT (_op_pm_source_web_init (init_block_ptr))

	obtype = Vos_Define_Object_Prstate ("proc state vars (pm_source_web)",
		sizeof (pm_source_web_state));
	*init_block_ptr = 0;

	FRET (obtype)
	}

VosT_Address
_op_pm_source_web_alloc (VosT_Obtype obtype, int init_block)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	pm_source_web_state * ptr;
	FIN_MT (_op_pm_source_web_alloc (obtype))

	ptr = (pm_source_web_state *)Vos_Alloc_Object (obtype);
	if (ptr != OPC_NIL)
		{
		ptr->_op_current_block = init_block;
#if defined (OPD_ALLOW_ODB)
		ptr->_op_current_state = "pm_source_web [INIT enter execs]";
#endif
		}
	FRET ((VosT_Address)ptr)
	}



void
_op_pm_source_web_svar (void * gen_ptr, const char * var_name, void ** var_p_ptr)
	{
	pm_source_web_state		*prs_ptr;

	FIN_MT (_op_pm_source_web_svar (gen_ptr, var_name, var_p_ptr))

	if (var_name == OPC_NIL)
		{
		*var_p_ptr = (void *)OPC_NIL;
		FOUT
		}
	prs_ptr = (pm_source_web_state *)gen_ptr;

	if (strcmp ("own_id" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->own_id);
		FOUT
		}
	if (strcmp ("requests_sent_hndl" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->requests_sent_hndl);
		FOUT
		}
	if (strcmp ("req_rate" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->req_rate);
		FOUT
		}
	if (strcmp ("requests_sent" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->requests_sent);
		FOUT
		}
	*var_p_ptr = (void *)OPC_NIL;

	FOUT
	}

