/* Process model C form file: pm_server_process.pr.c */
/* Portions of this file copyright 1986-2012 by OPNET Technologies, Inc. */


/*
 =========================== NOTE ==========================
 This file is automatically generated from pm_server_process.pr.m
 during a process model compilation.

 Do NOT manually edit this file.
 Manual edits will be lost during the next compilation.
 =========================== NOTE ==========================
*/



/* This variable carries the header into the object file */
const char pm_server_process_pr_c [] = "MIL_3_Tfile_Hdr_ 171A 30A op_runsim_dev 7 552C03E1 552C03E1 1 FTNK-B0013 s146147 0 0 none none 0 0 none 0 0 0 0 0 0 0 0 2b74 2                                                                                                                                                                                                                                                                                                                                                                                                 ";
#include <string.h>



/* OPNET system definitions */
#include <opnet.h>



/* Header Block */

#define PowerUp (op_intrpt_type() == OPC_INTRPT_BEGSIM) 
#define PacketArrival (op_intrpt_type() == OPC_INTRPT_STRM && op_intrpt_strm()==PckStream) 
#define DataPacketArrival (op_pk_total_size_get(tcp_packet_ptr)!=1)

/* End of Header Block */

#if !defined (VOSD_NO_FIN)
#undef	BIN
#undef	BOUT
#define	BIN		FIN_LOCAL_FIELD(_op_last_line_passed) = __LINE__ - _op_block_origin;
#define	BOUT	BIN
#define	BINIT	FIN_LOCAL_FIELD(_op_last_line_passed) = 0; _op_block_origin = __LINE__;
#else
#define	BINIT
#endif /* #if !defined (VOSD_NO_FIN) */



/* State variable definitions */
typedef struct
	{
	/* Internal state tracking for FSM */
	FSM_SYS_STATE
	/* State Variables */
	int	                    		PckStream                                       ;
	int	                    		SinkStream                                      ;
	int	                    		TransStream                                     ;
	int	                    		RecNextPckSeq                                   ;
	Boolean	                		DataPktArr                                      ;
	} pm_server_process_state;

#define PckStream               		op_sv_ptr->PckStream
#define SinkStream              		op_sv_ptr->SinkStream
#define TransStream             		op_sv_ptr->TransStream
#define RecNextPckSeq           		op_sv_ptr->RecNextPckSeq
#define DataPktArr              		op_sv_ptr->DataPktArr

/* These macro definitions will define a local variable called	*/
/* "op_sv_ptr" in each function containing a FIN statement.	*/
/* This variable points to the state variable data structure,	*/
/* and can be used from a C debugger to display their values.	*/
#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE
#define FIN_PREAMBLE_DEC	pm_server_process_state *op_sv_ptr;
#define FIN_PREAMBLE_CODE	\
		op_sv_ptr = ((pm_server_process_state *)(OP_SIM_CONTEXT_PTR->_op_mod_state_ptr));


/* No Function Block */

#if !defined (VOSD_NO_FIN)
enum { _op_block_origin = __LINE__ };
#endif

/* Undefine optional tracing in FIN/FOUT/FRET */
/* The FSM has its own tracing code and the other */
/* functions should not have any tracing.		  */
#undef FIN_TRACING
#define FIN_TRACING

#undef FOUTRET_TRACING
#define FOUTRET_TRACING

#if defined (__cplusplus)
extern "C" {
#endif
	void pm_server_process (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Obtype _op_pm_server_process_init (int * init_block_ptr);
	void _op_pm_server_process_diag (OP_SIM_CONTEXT_ARG_OPT);
	void _op_pm_server_process_terminate (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Address _op_pm_server_process_alloc (VosT_Obtype, int);
	void _op_pm_server_process_svar (void *, const char *, void **);


#if defined (__cplusplus)
} /* end of 'extern "C"' */
#endif




/* Process model interrupt handling procedure */


void
pm_server_process (OP_SIM_CONTEXT_ARG_OPT)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	FIN_MT (pm_server_process ());

		{
		/* Temporary Variables */
		int seq, type, src, dst;
		Packet* pkptr;
		Packet* ackptr;
		Packet* tcp_packet_ptr;
		Packet* ip_packet_ptr;
		/* End of Temporary Variables */


		FSM_ENTER_NO_VARS ("pm_server_process")

		FSM_BLOCK_SWITCH
			{
			/*---------------------------------------------------------*/
			/** state (INIT) enter executives **/
			FSM_STATE_ENTER_FORCED_NOLABEL (0, "INIT", "pm_server_process [INIT enter execs]")
				FSM_PROFILE_SECTION_IN ("pm_server_process [INIT enter execs]", state0_enter_exec)
				{
				/*ID of the connections Incoming*/
				Objid MyID, StrmID, OtherID;
				int index, InStreams,OutStreams;
				char ModuleName[64];
				MyID = op_id_self();
				
				
				InStreams = op_topo_assoc_count(MyID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_STRM);
				OutStreams = op_topo_assoc_count(MyID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_STRM);
				/*Find the Packet and AppData Streams*/
				
				for (index = 0; index < InStreams; index++)
				{
					/*Find the stream index at the specific association*/
					StrmID = op_topo_assoc(MyID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_STRM, index);
					
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_PTRX)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_PTRX,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "RX") == 0)
							{
								op_ima_obj_attr_get(StrmID, "dest stream", &PckStream);
							}
					}
				}
				
				for (index = 0; index < OutStreams; index++)
				{
					/*Find the stream index at the specific association*/
					StrmID = op_topo_assoc(MyID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_STRM, index);
					
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PROC)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PROC,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "Traffic Sink") == 0)
							{
								op_ima_obj_attr_get(StrmID, "src stream", &SinkStream);
								printf("SinkStream: %d\n",SinkStream);
							}
					}
					else if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PTTX)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PTTX,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "TX") == 0)
							{
								op_ima_obj_attr_get(StrmID, "src stream", &TransStream);
								printf("TransStream: %d\n",TransStream);
							}
					}
				}
				
				/*Initialization*/
				RecNextPckSeq=0;
				}
				FSM_PROFILE_SECTION_OUT (state0_enter_exec)

			/** state (INIT) exit executives **/
			FSM_STATE_EXIT_FORCED (0, "INIT", "pm_server_process [INIT exit execs]")


			/** state (INIT) transition processing **/
			FSM_TRANSIT_ONLY ((PowerUp), 1, state1_enter_exec, ;, INIT, "PowerUp", "", "INIT", "IDLE", "tr_0", "pm_server_process [INIT -> IDLE : PowerUp / ]")
				/*---------------------------------------------------------*/



			/** state (IDLE) enter executives **/
			FSM_STATE_ENTER_UNFORCED (1, "IDLE", state1_enter_exec, "pm_server_process [IDLE enter execs]")

			/** blocking after enter executives of unforced state. **/
			FSM_EXIT (3,"pm_server_process")


			/** state (IDLE) exit executives **/
			FSM_STATE_EXIT_UNFORCED (1, "IDLE", "pm_server_process [IDLE exit execs]")


			/** state (IDLE) transition processing **/
			FSM_TRANSIT_FORCE (2, state2_enter_exec, ;, "default", "", "IDLE", "REQ_ARR", "tr_10", "pm_server_process [IDLE -> REQ_ARR : default / ]")
				/*---------------------------------------------------------*/



			/** state (REQ_ARR) enter executives **/
			FSM_STATE_ENTER_FORCED (2, "REQ_ARR", state2_enter_exec, "pm_server_process [REQ_ARR enter execs]")
				FSM_PROFILE_SECTION_IN ("pm_server_process [REQ_ARR enter execs]", state2_enter_exec)
				{
				if ((PacketArrival)) 
					{
					ip_packet_ptr = op_pk_get(PckStream);
					op_pk_nfd_get(ip_packet_ptr, "type", &type); //type 0 means tcp packet
					op_pk_nfd_get(ip_packet_ptr, "src", &src);
					op_pk_nfd_get(ip_packet_ptr, "dst", &dst);
					op_pk_nfd_get_pkt (ip_packet_ptr, "data_field", &tcp_packet_ptr);
					if (DataPacketArrival && type==0 && dst==0)
						{
							/*Data packet arrival*/
							DataPktArr=DataPacketArrival;
							op_pk_nfd_get (tcp_packet_ptr, "seq", &seq);
							
							//printf("\n NODE %d IDLE DataPktArr of size=%d, seq=%d, Exp seq=%d", op_topo_parent(op_id_self()),op_pk_total_size_get(tcp_packet_ptr),seq,RecNextPckSeq);
							if(seq==RecNextPckSeq)
								{
								op_pk_nfd_get_pkt (tcp_packet_ptr, "data_field", &pkptr);
								op_pk_send(pkptr, SinkStream);
								if(RecNextPckSeq==0)
									RecNextPckSeq=1;
								else
									RecNextPckSeq=0;
								
								}
							else
								op_pk_destroy (tcp_packet_ptr);
								
							ackptr = op_pk_create_fmt ("pm_tcp_ack_packet");
							op_pk_nfd_set (ackptr, "seq", RecNextPckSeq);
							type=0;
							dst=src;
							src=0;
							op_pk_nfd_set_pkt (ip_packet_ptr, "data_field", ackptr);
							op_pk_nfd_set(ip_packet_ptr, "type", type);
							op_pk_nfd_set(ip_packet_ptr, "src", src);
							op_pk_nfd_set(ip_packet_ptr, "dst", dst);
							op_pk_send(ip_packet_ptr, TransStream);
						}
					else if(type==0)
						{
							/*ACK packet arrival*/
							op_pk_nfd_get_pkt (ip_packet_ptr, "data_field", &tcp_packet_ptr);
							op_pk_nfd_get (tcp_packet_ptr, "seq", &seq);
							printf("\n NODE %d IDLE AckArr - LOGICAL ERROR! of size=%d seq=%d",op_topo_parent(op_id_self()),op_pk_total_size_get (tcp_packet_ptr), seq);
							
						}
					
					}
				}
				FSM_PROFILE_SECTION_OUT (state2_enter_exec)

			/** state (REQ_ARR) exit executives **/
			FSM_STATE_EXIT_FORCED (2, "REQ_ARR", "pm_server_process [REQ_ARR exit execs]")


			/** state (REQ_ARR) transition processing **/
			FSM_TRANSIT_FORCE (1, state1_enter_exec, ;, "default", "", "REQ_ARR", "IDLE", "tr_11", "pm_server_process [REQ_ARR -> IDLE : default / ]")
				/*---------------------------------------------------------*/



			}


		FSM_EXIT (0,"pm_server_process")
		}
	}




void
_op_pm_server_process_diag (OP_SIM_CONTEXT_ARG_OPT)
	{
	/* No Diagnostic Block */
	}




void
_op_pm_server_process_terminate (OP_SIM_CONTEXT_ARG_OPT)
	{

	FIN_MT (_op_pm_server_process_terminate ())


	/* No Termination Block */

	Vos_Poolmem_Dealloc (op_sv_ptr);

	FOUT
	}


/* Undefine shortcuts to state variables to avoid */
/* syntax error in direct access to fields of */
/* local variable prs_ptr in _op_pm_server_process_svar function. */
#undef PckStream
#undef SinkStream
#undef TransStream
#undef RecNextPckSeq
#undef DataPktArr

#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE

#define FIN_PREAMBLE_DEC
#define FIN_PREAMBLE_CODE

VosT_Obtype
_op_pm_server_process_init (int * init_block_ptr)
	{
	VosT_Obtype obtype = OPC_NIL;
	FIN_MT (_op_pm_server_process_init (init_block_ptr))

	obtype = Vos_Define_Object_Prstate ("proc state vars (pm_server_process)",
		sizeof (pm_server_process_state));
	*init_block_ptr = 0;

	FRET (obtype)
	}

VosT_Address
_op_pm_server_process_alloc (VosT_Obtype obtype, int init_block)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	pm_server_process_state * ptr;
	FIN_MT (_op_pm_server_process_alloc (obtype))

	ptr = (pm_server_process_state *)Vos_Alloc_Object (obtype);
	if (ptr != OPC_NIL)
		{
		ptr->_op_current_block = init_block;
#if defined (OPD_ALLOW_ODB)
		ptr->_op_current_state = "pm_server_process [INIT enter execs]";
#endif
		}
	FRET ((VosT_Address)ptr)
	}



void
_op_pm_server_process_svar (void * gen_ptr, const char * var_name, void ** var_p_ptr)
	{
	pm_server_process_state		*prs_ptr;

	FIN_MT (_op_pm_server_process_svar (gen_ptr, var_name, var_p_ptr))

	if (var_name == OPC_NIL)
		{
		*var_p_ptr = (void *)OPC_NIL;
		FOUT
		}
	prs_ptr = (pm_server_process_state *)gen_ptr;

	if (strcmp ("PckStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->PckStream);
		FOUT
		}
	if (strcmp ("SinkStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->SinkStream);
		FOUT
		}
	if (strcmp ("TransStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->TransStream);
		FOUT
		}
	if (strcmp ("RecNextPckSeq" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->RecNextPckSeq);
		FOUT
		}
	if (strcmp ("DataPktArr" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->DataPktArr);
		FOUT
		}
	*var_p_ptr = (void *)OPC_NIL;

	FOUT
	}

