/* Process model C form file: pm_utp_user_process.pr.c */
/* Portions of this file copyright 1986-2012 by OPNET Technologies, Inc. */


/*
 =========================== NOTE ==========================
 This file is automatically generated from pm_utp_user_process.pr.m
 during a process model compilation.

 Do NOT manually edit this file.
 Manual edits will be lost during the next compilation.
 =========================== NOTE ==========================
*/



/* This variable carries the header into the object file */
const char pm_utp_user_process_pr_c [] = "MIL_3_Tfile_Hdr_ 171A 30A modeler 7 556646BC 556646BC 1 FTNK-B0013 s146147 0 0 none none 0 0 none 0 0 0 0 0 0 0 0 2b74 2                                                                                                                                                                                                                                                                                                                                                                                                       ";
#include <string.h>



/* OPNET system definitions */
#include <opnet.h>



/* Header Block */

#define PowerUp (op_intrpt_type() == OPC_INTRPT_BEGSIM) 
#define PacketArrival (op_intrpt_type() == OPC_INTRPT_STRM)


#define BuffUL 0
#define BuffDL 1
#define TransOver (op_intrpt_type() == OPC_INTRPT_SELF) 

#define TCP_DATA 0
#define UTP_DATA 1
#define WEB_DATA 2

/* End of Header Block */

#if !defined (VOSD_NO_FIN)
#undef	BIN
#undef	BOUT
#define	BIN		FIN_LOCAL_FIELD(_op_last_line_passed) = __LINE__ - _op_block_origin;
#define	BOUT	BIN
#define	BINIT	FIN_LOCAL_FIELD(_op_last_line_passed) = 0; _op_block_origin = __LINE__;
#else
#define	BINIT
#endif /* #if !defined (VOSD_NO_FIN) */



/* State variable definitions */
typedef struct
	{
	/* Internal state tracking for FSM */
	FSM_SYS_STATE
	/* State Variables */
	int	                    		InternetINStream                                ;
	int	                    		InternetOUTStream                               ;
	int	                    		RXStream                                        ;
	int	                    		TXStream                                        ;
	double	                 		UpLinkCap                                       ;
	Evhandle	               		TrFinU                                          ;
	int	                    		RXuTPStream                                     ;
	int	                    		TXuTPStream                                     ;
	int	                    		RXwebStream                                     ;
	int	                    		TXwebStream                                     ;
	double	                 		DownLinkCap                                     ;
	Evhandle	               		TrFinD                                          ;
	Stathandle	             		packets_drop_hndl                               ;
	double	                 		packets_drop                                    ;
	int	                    		RXTCPStream                                     ;
	int	                    		TXTCPStream                                     ;
	} pm_utp_user_process_state;

#define InternetINStream        		op_sv_ptr->InternetINStream
#define InternetOUTStream       		op_sv_ptr->InternetOUTStream
#define RXStream                		op_sv_ptr->RXStream
#define TXStream                		op_sv_ptr->TXStream
#define UpLinkCap               		op_sv_ptr->UpLinkCap
#define TrFinU                  		op_sv_ptr->TrFinU
#define RXuTPStream             		op_sv_ptr->RXuTPStream
#define TXuTPStream             		op_sv_ptr->TXuTPStream
#define RXwebStream             		op_sv_ptr->RXwebStream
#define TXwebStream             		op_sv_ptr->TXwebStream
#define DownLinkCap             		op_sv_ptr->DownLinkCap
#define TrFinD                  		op_sv_ptr->TrFinD
#define packets_drop_hndl       		op_sv_ptr->packets_drop_hndl
#define packets_drop            		op_sv_ptr->packets_drop
#define RXTCPStream             		op_sv_ptr->RXTCPStream
#define TXTCPStream             		op_sv_ptr->TXTCPStream

/* These macro definitions will define a local variable called	*/
/* "op_sv_ptr" in each function containing a FIN statement.	*/
/* This variable points to the state variable data structure,	*/
/* and can be used from a C debugger to display their values.	*/
#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE
#define FIN_PREAMBLE_DEC	pm_utp_user_process_state *op_sv_ptr;
#define FIN_PREAMBLE_CODE	\
		op_sv_ptr = ((pm_utp_user_process_state *)(OP_SIM_CONTEXT_PTR->_op_mod_state_ptr));


/* No Function Block */

#if !defined (VOSD_NO_FIN)
enum { _op_block_origin = __LINE__ };
#endif

/* Undefine optional tracing in FIN/FOUT/FRET */
/* The FSM has its own tracing code and the other */
/* functions should not have any tracing.		  */
#undef FIN_TRACING
#define FIN_TRACING

#undef FOUTRET_TRACING
#define FOUTRET_TRACING

#if defined (__cplusplus)
extern "C" {
#endif
	void pm_utp_user_process (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Obtype _op_pm_utp_user_process_init (int * init_block_ptr);
	void _op_pm_utp_user_process_diag (OP_SIM_CONTEXT_ARG_OPT);
	void _op_pm_utp_user_process_terminate (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Address _op_pm_utp_user_process_alloc (VosT_Obtype, int);
	void _op_pm_utp_user_process_svar (void *, const char *, void **);


#if defined (__cplusplus)
} /* end of 'extern "C"' */
#endif




/* Process model interrupt handling procedure */


void
pm_utp_user_process (OP_SIM_CONTEXT_ARG_OPT)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	FIN_MT (pm_utp_user_process ());

		{
		/* Temporary Variables */
		Packet *pkptr;
		Packet *ip_packet;
		/* End of Temporary Variables */


		FSM_ENTER ("pm_utp_user_process")

		FSM_BLOCK_SWITCH
			{
			/*---------------------------------------------------------*/
			/** state (INIT) enter executives **/
			FSM_STATE_ENTER_FORCED_NOLABEL (0, "INIT", "pm_utp_user_process [INIT enter execs]")
				FSM_PROFILE_SECTION_IN ("pm_utp_user_process [INIT enter execs]", state0_enter_exec)
				{
				/*ID of the connections Incoming*/
				Objid MyID, StrmID, OtherID;
				int index, InStreams,OutStreams;
				char ModuleName[64];
				MyID = op_id_self();
				
				op_ima_obj_attr_get (MyID, "UpLinkCap", &UpLinkCap);
				op_ima_obj_attr_get (MyID, "DownLinkCap", &DownLinkCap);
				packets_drop_hndl   = op_stat_reg ("User.Packets drop",		OPC_STAT_INDEX_NONE, OPC_STAT_LOCAL);
				packets_drop=0.0;
				InStreams = op_topo_assoc_count(MyID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_STRM);
				OutStreams = op_topo_assoc_count(MyID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_STRM);
				/*Find the Packet and AppData Streams*/
				
				for (index = 0; index < InStreams; index++)
				{
					/*Find the stream index at the specific association*/
					StrmID = op_topo_assoc(MyID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_STRM, index);
					
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_QUEUE)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_QUEUE,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "INTERNET Cloud") == 0)
							{
								op_ima_obj_attr_get(StrmID, "dest stream", &InternetINStream);
								printf("InternetINStream: %d\n",InternetINStream);
							}
					}
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_PTRX)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_PTRX,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "RX_uTP") == 0)
							{
								op_ima_obj_attr_get(StrmID, "dest stream", &RXuTPStream);
								printf("RXuTPStream: %d\n",RXuTPStream);
							}
					}
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_PTRX)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_PTRX,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "RX_WEB") == 0)
							{
								op_ima_obj_attr_get(StrmID, "dest stream", &RXwebStream);
								printf("RXwebStream: %d\n",RXwebStream);
							}
					}
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_PTRX)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_PTRX,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "RX_TCP") == 0)
							{
								op_ima_obj_attr_get(StrmID, "dest stream", &RXTCPStream);
								printf("RXTCPStream: %d\n",RXTCPStream);
							}
					}
				}
				
				for (index = 0; index < OutStreams; index++)
				{
					/*Find the stream index at the specific association*/
					StrmID = op_topo_assoc(MyID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_STRM, index);
					
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_QUEUE)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_QUEUE,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "INTERNET Cloud") == 0)
							{
								op_ima_obj_attr_get(StrmID, "src stream", &InternetOUTStream);
								printf("InternetOUTStream: %d\n",InternetOUTStream);
							}
					}
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PTTX)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PTTX,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "TX_uTP") == 0)
							{
								op_ima_obj_attr_get(StrmID, "src stream", &TXuTPStream);
								printf("TXuTPStream: %d\n",TXuTPStream);
							}
					}
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PTTX)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PTTX,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "TX_WEB") == 0)
							{
								op_ima_obj_attr_get(StrmID, "src stream", &TXwebStream);
								printf("TXwebStream: %d\n",TXwebStream);
							}
					}
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PTTX)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PTTX,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "TX_TCP") == 0)
							{
								op_ima_obj_attr_get(StrmID, "src stream", &TXTCPStream);
								printf("TXTCPStream: %d\n",TXTCPStream);
							}
					}
				}
				op_stat_write (packets_drop_hndl, 0);
				}
				FSM_PROFILE_SECTION_OUT (state0_enter_exec)

			/** state (INIT) exit executives **/
			FSM_STATE_EXIT_FORCED (0, "INIT", "pm_utp_user_process [INIT exit execs]")


			/** state (INIT) transition processing **/
			FSM_TRANSIT_ONLY ((PowerUp), 1, state1_enter_exec, ;, INIT, "PowerUp", "", "INIT", "IDLE", "tr_0", "pm_utp_user_process [INIT -> IDLE : PowerUp / ]")
				/*---------------------------------------------------------*/



			/** state (IDLE) enter executives **/
			FSM_STATE_ENTER_UNFORCED (1, "IDLE", state1_enter_exec, "pm_utp_user_process [IDLE enter execs]")
				FSM_PROFILE_SECTION_IN ("pm_utp_user_process [IDLE enter execs]", state1_enter_exec)
				{
				
				}
				FSM_PROFILE_SECTION_OUT (state1_enter_exec)

			/** blocking after enter executives of unforced state. **/
			FSM_EXIT (3,"pm_utp_user_process")


			/** state (IDLE) exit executives **/
			FSM_STATE_EXIT_UNFORCED (1, "IDLE", "pm_utp_user_process [IDLE exit execs]")
				FSM_PROFILE_SECTION_IN ("pm_utp_user_process [IDLE exit execs]", state1_exit_exec)
				{
				//printf("\n Packet arrival");
				}
				FSM_PROFILE_SECTION_OUT (state1_exit_exec)


			/** state (IDLE) transition processing **/
			FSM_TRANSIT_ONLY ((PacketArrival), 2, state2_enter_exec, ;, IDLE, "PacketArrival", "", "IDLE", "PKT_HND", "tr_10", "pm_utp_user_process [IDLE -> PKT_HND : PacketArrival / ]")
				/*---------------------------------------------------------*/



			/** state (PKT_HND) enter executives **/
			FSM_STATE_ENTER_FORCED (2, "PKT_HND", state2_enter_exec, "pm_utp_user_process [PKT_HND enter execs]")
				FSM_PROFILE_SECTION_IN ("pm_utp_user_process [PKT_HND enter execs]", state2_enter_exec)
				{
				int src=0;
				int dst=0;
				int type=0;
				int seq_num,ack_num;
				Packet* est_pkt;
					/*DOWNLINK, so PASS to the network*/
				if(op_intrpt_strm () == InternetINStream)
					{
					/* Obtain the incoming packet.	*/
					ip_packet = op_pk_get (InternetINStream);
					est_pkt=op_pk_copy(ip_packet);
					
					if(op_subq_pk_insert(BuffDL, ip_packet, OPC_QPOS_TAIL)!= OPC_QINS_OK)
						{
						op_pk_destroy (ip_packet);
						//printf("\n RXStream packet Destroyed");
						}
					else if(op_subq_stat (BuffDL, OPC_QSTAT_PKSIZE)==1)
						{
						TrFinD=op_intrpt_schedule_self(op_sim_time() + op_pk_total_size_get(est_pkt)/DownLinkCap, BuffDL);
				
						}
					op_pk_destroy (est_pkt);
					}
				
					/*UPLINK*/
				else 
					{
					/* Obtain the incoming packet.	*/
					RXStream=op_intrpt_strm ();
					pkptr = op_pk_get (RXStream);
					
					est_pkt=op_pk_copy(pkptr);
					ip_packet = op_pk_create_fmt ("pm_ip_packet");
					if(RXStream==RXwebStream)
						{
						type=WEB_DATA;
						dst=WEB_DATA;
						}
					else if(RXStream==RXuTPStream)
						{
						type=UTP_DATA;
						dst=UTP_DATA;
						}
					else if(RXStream==RXTCPStream)
						{
						type=TCP_DATA;
						dst=TCP_DATA;
						}
					op_pk_nfd_set (ip_packet, "src",RXStream);
					op_pk_nfd_set (ip_packet, "dst",dst);
					op_pk_nfd_set (ip_packet, "type",type);	
					op_pk_nfd_set_pkt (ip_packet, "data_field", pkptr);
					
					//printf("\n USER IN RXSTREAM, BUFF: %f, size: %d, type=%d, timestamp:%f", op_subq_stat (BuffUL, OPC_QSTAT_PKSIZE), op_pk_total_size_get(pkptr)/8,type,op_sim_time());
					
					
					if(op_subq_pk_insert(BuffUL, ip_packet, OPC_QPOS_TAIL)!= OPC_QINS_OK)
						{
						op_pk_destroy (ip_packet);
						op_stat_write (packets_drop_hndl, packets_drop=packets_drop + 1.0);
						op_pk_nfd_get (est_pkt, "ack_num",&ack_num);
						op_pk_nfd_get (est_pkt, "seq_num",&seq_num);
						if(type==WEB_DATA)
							{
							//printf("\n RXStream WEB_DATA packet Destroyed s%d,a%d",seq_num,ack_num);
							}
						else 
							{
							//printf("\n RXStream packet Destroyed s%d,a%d",seq_num,ack_num);
							}
						
						}
					else if(op_subq_stat (BuffUL, OPC_QSTAT_PKSIZE)==1)
						{
						TrFinU=op_intrpt_schedule_self(op_sim_time() + op_pk_total_size_get(est_pkt)/UpLinkCap, BuffUL);
				
						}
				
					op_pk_destroy (est_pkt);
					}
				}
				FSM_PROFILE_SECTION_OUT (state2_enter_exec)

			/** state (PKT_HND) exit executives **/
			FSM_STATE_EXIT_FORCED (2, "PKT_HND", "pm_utp_user_process [PKT_HND exit execs]")


			/** state (PKT_HND) transition processing **/
			FSM_PROFILE_SECTION_IN ("pm_utp_user_process [PKT_HND trans conditions]", state2_trans_conds)
			FSM_INIT_COND ( (op_subq_stat (0, OPC_QSTAT_PKSIZE)!=0 || op_subq_stat (1, OPC_QSTAT_PKSIZE)!=0))
			FSM_TEST_COND (op_subq_stat (0, OPC_QSTAT_PKSIZE)==0 && op_subq_stat (1, OPC_QSTAT_PKSIZE)==0)
			FSM_TEST_LOGIC ("PKT_HND")
			FSM_PROFILE_SECTION_OUT (state2_trans_conds)

			FSM_TRANSIT_SWITCH
				{
				FSM_CASE_TRANSIT (0, 3, state3_enter_exec, ;, " (op_subq_stat (0, OPC_QSTAT_PKSIZE)!=0 || op_subq_stat (1, OPC_QSTAT_PKSIZE)!=0)", "", "PKT_HND", "WAIT_TRA", "tr_12", "pm_utp_user_process [PKT_HND -> WAIT_TRA :  (op_subq_stat (0, OPC_QSTAT_PKSIZE)!=0 || op_subq_stat (1, OPC_QSTAT_PKSIZE)!=0) / ]")
				FSM_CASE_TRANSIT (1, 1, state1_enter_exec, ;, "op_subq_stat (0, OPC_QSTAT_PKSIZE)==0 && op_subq_stat (1, OPC_QSTAT_PKSIZE)==0", "", "PKT_HND", "IDLE", "tr_13", "pm_utp_user_process [PKT_HND -> IDLE : op_subq_stat (0, OPC_QSTAT_PKSIZE)==0 && op_subq_stat (1, OPC_QSTAT_PKSIZE)==0 / ]")
				}
				/*---------------------------------------------------------*/



			/** state (WAIT_TRA) enter executives **/
			FSM_STATE_ENTER_UNFORCED (3, "WAIT_TRA", state3_enter_exec, "pm_utp_user_process [WAIT_TRA enter execs]")
				FSM_PROFILE_SECTION_IN ("pm_utp_user_process [WAIT_TRA enter execs]", state3_enter_exec)
				{
				//printf("\n In WAIT_TRA");
				}
				FSM_PROFILE_SECTION_OUT (state3_enter_exec)

			/** blocking after enter executives of unforced state. **/
			FSM_EXIT (7,"pm_utp_user_process")


			/** state (WAIT_TRA) exit executives **/
			FSM_STATE_EXIT_UNFORCED (3, "WAIT_TRA", "pm_utp_user_process [WAIT_TRA exit execs]")


			/** state (WAIT_TRA) transition processing **/
			FSM_PROFILE_SECTION_IN ("pm_utp_user_process [WAIT_TRA trans conditions]", state3_trans_conds)
			FSM_INIT_COND (PacketArrival)
			FSM_TEST_COND (TransOver)
			FSM_TEST_LOGIC ("WAIT_TRA")
			FSM_PROFILE_SECTION_OUT (state3_trans_conds)

			FSM_TRANSIT_SWITCH
				{
				FSM_CASE_TRANSIT (0, 2, state2_enter_exec, ;, "PacketArrival", "", "WAIT_TRA", "PKT_HND", "tr_15", "pm_utp_user_process [WAIT_TRA -> PKT_HND : PacketArrival / ]")
				FSM_CASE_TRANSIT (1, 4, state4_enter_exec, ;, "TransOver", "", "WAIT_TRA", "SEND", "tr_16", "pm_utp_user_process [WAIT_TRA -> SEND : TransOver / ]")
				}
				/*---------------------------------------------------------*/



			/** state (SEND) enter executives **/
			FSM_STATE_ENTER_FORCED (4, "SEND", state4_enter_exec, "pm_utp_user_process [SEND enter execs]")
				FSM_PROFILE_SECTION_IN ("pm_utp_user_process [SEND enter execs]", state4_enter_exec)
				{
				int type=0,dst;
				Packet* est_pkt;
				if(op_intrpt_code ()==BuffUL)
					{
					/* Send the incoming packet.	*/
					pkptr = op_subq_pk_remove (BuffUL, OPC_QPOS_HEAD);
					op_pk_send (pkptr, InternetOUTStream);
					//printf("\n Packet finished transmission");
					if(op_subq_stat (BuffUL, OPC_QSTAT_PKSIZE)!=0)
						{
						est_pkt = op_subq_pk_access (BuffUL, OPC_QPOS_HEAD);
						TrFinU=op_intrpt_schedule_self(op_sim_time() + op_pk_total_size_get(est_pkt)/UpLinkCap, BuffUL);
						//printf("\n SEND InternetOUTStream BUFFER SIZE = %f",op_subq_stat (BuffUL, OPC_QSTAT_PKSIZE));
						}
					
					}
				else if(op_intrpt_code ()==BuffDL)
					{
					ip_packet= op_subq_pk_remove (BuffDL, OPC_QPOS_HEAD);
					/* Send the incoming packet.	*/
					op_pk_nfd_get_pkt (ip_packet, "data_field", &pkptr);
					op_pk_nfd_access(ip_packet, "type", &type);
					if(type==WEB_DATA)
						{
						dst=TXwebStream;
						}
					else if(type==UTP_DATA)
						{
						dst=TXuTPStream;
						}
					else if(type==TCP_DATA)
						{
						dst=TXTCPStream;
						}
					
					//printf("\n USER INTinStream, dst: %d", dst);
					op_pk_send (pkptr, dst);
					op_pk_destroy (ip_packet);
					
					if(op_subq_stat (BuffDL, OPC_QSTAT_PKSIZE)!=0)
						{
						est_pkt = op_subq_pk_access (BuffDL, OPC_QPOS_HEAD);
						TrFinD=op_intrpt_schedule_self(op_sim_time() + op_pk_total_size_get(est_pkt)/DownLinkCap, BuffDL);
						//printf("\n SERV Next Packet starts transmission");
						}
					
					}
				}
				FSM_PROFILE_SECTION_OUT (state4_enter_exec)

			/** state (SEND) exit executives **/
			FSM_STATE_EXIT_FORCED (4, "SEND", "pm_utp_user_process [SEND exit execs]")


			/** state (SEND) transition processing **/
			FSM_PROFILE_SECTION_IN ("pm_utp_user_process [SEND trans conditions]", state4_trans_conds)
			FSM_INIT_COND (op_subq_stat (0, OPC_QSTAT_PKSIZE)==0 && op_subq_stat (1, OPC_QSTAT_PKSIZE)==0)
			FSM_TEST_COND (op_subq_stat (0, OPC_QSTAT_PKSIZE)!=0 || op_subq_stat (1, OPC_QSTAT_PKSIZE)!=0)
			FSM_TEST_LOGIC ("SEND")
			FSM_PROFILE_SECTION_OUT (state4_trans_conds)

			FSM_TRANSIT_SWITCH
				{
				FSM_CASE_TRANSIT (0, 1, state1_enter_exec, ;, "op_subq_stat (0, OPC_QSTAT_PKSIZE)==0 && op_subq_stat (1, OPC_QSTAT_PKSIZE)==0", "", "SEND", "IDLE", "tr_17", "pm_utp_user_process [SEND -> IDLE : op_subq_stat (0, OPC_QSTAT_PKSIZE)==0 && op_subq_stat (1, OPC_QSTAT_PKSIZE)==0 / ]")
				FSM_CASE_TRANSIT (1, 3, state3_enter_exec, ;, "op_subq_stat (0, OPC_QSTAT_PKSIZE)!=0 || op_subq_stat (1, OPC_QSTAT_PKSIZE)!=0", "", "SEND", "WAIT_TRA", "tr_18", "pm_utp_user_process [SEND -> WAIT_TRA : op_subq_stat (0, OPC_QSTAT_PKSIZE)!=0 || op_subq_stat (1, OPC_QSTAT_PKSIZE)!=0 / ]")
				}
				/*---------------------------------------------------------*/



			}


		FSM_EXIT (0,"pm_utp_user_process")
		}
	}




void
_op_pm_utp_user_process_diag (OP_SIM_CONTEXT_ARG_OPT)
	{
	/* No Diagnostic Block */
	}




void
_op_pm_utp_user_process_terminate (OP_SIM_CONTEXT_ARG_OPT)
	{

	FIN_MT (_op_pm_utp_user_process_terminate ())


	/* No Termination Block */

	Vos_Poolmem_Dealloc (op_sv_ptr);

	FOUT
	}


/* Undefine shortcuts to state variables to avoid */
/* syntax error in direct access to fields of */
/* local variable prs_ptr in _op_pm_utp_user_process_svar function. */
#undef InternetINStream
#undef InternetOUTStream
#undef RXStream
#undef TXStream
#undef UpLinkCap
#undef TrFinU
#undef RXuTPStream
#undef TXuTPStream
#undef RXwebStream
#undef TXwebStream
#undef DownLinkCap
#undef TrFinD
#undef packets_drop_hndl
#undef packets_drop
#undef RXTCPStream
#undef TXTCPStream

#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE

#define FIN_PREAMBLE_DEC
#define FIN_PREAMBLE_CODE

VosT_Obtype
_op_pm_utp_user_process_init (int * init_block_ptr)
	{
	VosT_Obtype obtype = OPC_NIL;
	FIN_MT (_op_pm_utp_user_process_init (init_block_ptr))

	obtype = Vos_Define_Object_Prstate ("proc state vars (pm_utp_user_process)",
		sizeof (pm_utp_user_process_state));
	*init_block_ptr = 0;

	FRET (obtype)
	}

VosT_Address
_op_pm_utp_user_process_alloc (VosT_Obtype obtype, int init_block)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	pm_utp_user_process_state * ptr;
	FIN_MT (_op_pm_utp_user_process_alloc (obtype))

	ptr = (pm_utp_user_process_state *)Vos_Alloc_Object (obtype);
	if (ptr != OPC_NIL)
		{
		ptr->_op_current_block = init_block;
#if defined (OPD_ALLOW_ODB)
		ptr->_op_current_state = "pm_utp_user_process [INIT enter execs]";
#endif
		}
	FRET ((VosT_Address)ptr)
	}



void
_op_pm_utp_user_process_svar (void * gen_ptr, const char * var_name, void ** var_p_ptr)
	{
	pm_utp_user_process_state		*prs_ptr;

	FIN_MT (_op_pm_utp_user_process_svar (gen_ptr, var_name, var_p_ptr))

	if (var_name == OPC_NIL)
		{
		*var_p_ptr = (void *)OPC_NIL;
		FOUT
		}
	prs_ptr = (pm_utp_user_process_state *)gen_ptr;

	if (strcmp ("InternetINStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->InternetINStream);
		FOUT
		}
	if (strcmp ("InternetOUTStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->InternetOUTStream);
		FOUT
		}
	if (strcmp ("RXStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->RXStream);
		FOUT
		}
	if (strcmp ("TXStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->TXStream);
		FOUT
		}
	if (strcmp ("UpLinkCap" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->UpLinkCap);
		FOUT
		}
	if (strcmp ("TrFinU" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->TrFinU);
		FOUT
		}
	if (strcmp ("RXuTPStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->RXuTPStream);
		FOUT
		}
	if (strcmp ("TXuTPStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->TXuTPStream);
		FOUT
		}
	if (strcmp ("RXwebStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->RXwebStream);
		FOUT
		}
	if (strcmp ("TXwebStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->TXwebStream);
		FOUT
		}
	if (strcmp ("DownLinkCap" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->DownLinkCap);
		FOUT
		}
	if (strcmp ("TrFinD" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->TrFinD);
		FOUT
		}
	if (strcmp ("packets_drop_hndl" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->packets_drop_hndl);
		FOUT
		}
	if (strcmp ("packets_drop" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->packets_drop);
		FOUT
		}
	if (strcmp ("RXTCPStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->RXTCPStream);
		FOUT
		}
	if (strcmp ("TXTCPStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->TXTCPStream);
		FOUT
		}
	*var_p_ptr = (void *)OPC_NIL;

	FOUT
	}

