/* Process model C form file: pm_utp_internet_process.pr.c */
/* Portions of this file copyright 1986-2012 by OPNET Technologies, Inc. */


/*
 =========================== NOTE ==========================
 This file is automatically generated from pm_utp_internet_process.pr.m
 during a process model compilation.

 Do NOT manually edit this file.
 Manual edits will be lost during the next compilation.
 =========================== NOTE ==========================
*/



/* This variable carries the header into the object file */
const char pm_utp_internet_process_pr_c [] = "MIL_3_Tfile_Hdr_ 171A 30A modeler 7 5568066B 5568066B 1 FTNK-B0013 s146147 0 0 none none 0 0 none 0 0 0 0 0 0 0 0 2b74 2                                                                                                                                                                                                                                                                                                                                                                                                       ";
#include <string.h>



/* OPNET system definitions */
#include <opnet.h>



/* Header Block */

#define PowerUp (op_intrpt_type() == OPC_INTRPT_BEGSIM) 
#define PacketArrival (op_intrpt_type() == OPC_INTRPT_STRM)

#define BuffDLWEB 0
#define BuffDL 1
#define BuffULWEB 2
#define BuffUL 3
#define TransOver (op_intrpt_type() == OPC_INTRPT_SELF) 
#define EmptyQueue (op_subq_stat (0, OPC_QSTAT_PKSIZE)==0 && op_subq_stat (1, OPC_QSTAT_PKSIZE)==0 && op_subq_stat (2, OPC_QSTAT_PKSIZE)==0 && op_subq_stat (3, OPC_QSTAT_PKSIZE)==0)
#define NotEmptyQueue ( op_subq_stat (0, OPC_QSTAT_PKSIZE)!=0 || op_subq_stat (1, OPC_QSTAT_PKSIZE)!=0 || op_subq_stat (2, OPC_QSTAT_PKSIZE)!=0 || op_subq_stat (3, OPC_QSTAT_PKSIZE)!=0)

#define TCP_DATA 0
#define UTP_DATA 1
#define WEB_DATA 2

/* End of Header Block */

#if !defined (VOSD_NO_FIN)
#undef	BIN
#undef	BOUT
#define	BIN		FIN_LOCAL_FIELD(_op_last_line_passed) = __LINE__ - _op_block_origin;
#define	BOUT	BIN
#define	BINIT	FIN_LOCAL_FIELD(_op_last_line_passed) = 0; _op_block_origin = __LINE__;
#else
#define	BINIT
#endif /* #if !defined (VOSD_NO_FIN) */



/* State variable definitions */
typedef struct
	{
	/* Internal state tracking for FSM */
	FSM_SYS_STATE
	/* State Variables */
	int	                    		UserINStream                                    ;
	int	                    		UserOUTStream                                   ;
	int	                    		RXservWEBStream                                 ;
	int	                    		TXservWEBStream                                 ;
	Evhandle	               		TrFinD                                          ;
	double	                 		IntDelay                                        ;
	Evhandle	               		TrFinU                                          ;
	int	                    		RXservUTPStream                                 ;
	int	                    		TXservUTPStream                                 ;
	int	                    		RXservTCPStream                                 ;
	int	                    		TXservTCPStream                                 ;
	double	                 		IntWebDelay                                     ;
	int	                    		jitter_mode                                     ;
	} pm_utp_internet_process_state;

#define UserINStream            		op_sv_ptr->UserINStream
#define UserOUTStream           		op_sv_ptr->UserOUTStream
#define RXservWEBStream         		op_sv_ptr->RXservWEBStream
#define TXservWEBStream         		op_sv_ptr->TXservWEBStream
#define TrFinD                  		op_sv_ptr->TrFinD
#define IntDelay                		op_sv_ptr->IntDelay
#define TrFinU                  		op_sv_ptr->TrFinU
#define RXservUTPStream         		op_sv_ptr->RXservUTPStream
#define TXservUTPStream         		op_sv_ptr->TXservUTPStream
#define RXservTCPStream         		op_sv_ptr->RXservTCPStream
#define TXservTCPStream         		op_sv_ptr->TXservTCPStream
#define IntWebDelay             		op_sv_ptr->IntWebDelay
#define jitter_mode             		op_sv_ptr->jitter_mode

/* These macro definitions will define a local variable called	*/
/* "op_sv_ptr" in each function containing a FIN statement.	*/
/* This variable points to the state variable data structure,	*/
/* and can be used from a C debugger to display their values.	*/
#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE
#define FIN_PREAMBLE_DEC	pm_utp_internet_process_state *op_sv_ptr;
#define FIN_PREAMBLE_CODE	\
		op_sv_ptr = ((pm_utp_internet_process_state *)(OP_SIM_CONTEXT_PTR->_op_mod_state_ptr));


/* No Function Block */

#if !defined (VOSD_NO_FIN)
enum { _op_block_origin = __LINE__ };
#endif

/* Undefine optional tracing in FIN/FOUT/FRET */
/* The FSM has its own tracing code and the other */
/* functions should not have any tracing.		  */
#undef FIN_TRACING
#define FIN_TRACING

#undef FOUTRET_TRACING
#define FOUTRET_TRACING

#if defined (__cplusplus)
extern "C" {
#endif
	void pm_utp_internet_process (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Obtype _op_pm_utp_internet_process_init (int * init_block_ptr);
	void _op_pm_utp_internet_process_diag (OP_SIM_CONTEXT_ARG_OPT);
	void _op_pm_utp_internet_process_terminate (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Address _op_pm_utp_internet_process_alloc (VosT_Obtype, int);
	void _op_pm_utp_internet_process_svar (void *, const char *, void **);


#if defined (__cplusplus)
} /* end of 'extern "C"' */
#endif




/* Process model interrupt handling procedure */


void
pm_utp_internet_process (OP_SIM_CONTEXT_ARG_OPT)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	FIN_MT (pm_utp_internet_process ());

		{
		/* Temporary Variables */
		Packet *pkptr;
		/* End of Temporary Variables */


		FSM_ENTER ("pm_utp_internet_process")

		FSM_BLOCK_SWITCH
			{
			/*---------------------------------------------------------*/
			/** state (INIT) enter executives **/
			FSM_STATE_ENTER_FORCED_NOLABEL (0, "INIT", "pm_utp_internet_process [INIT enter execs]")
				FSM_PROFILE_SECTION_IN ("pm_utp_internet_process [INIT enter execs]", state0_enter_exec)
				{
				/*ID of the connections Incoming*/
				Objid MyID, StrmID, OtherID;
				int index, InStreams,OutStreams;
				char ModuleName[64];
				MyID = op_id_self();
				
				op_ima_obj_attr_get (MyID, "IntDelay", &IntDelay);
				op_ima_obj_attr_get (MyID, "jitter_mode", &jitter_mode);
				op_ima_obj_attr_get (MyID, "IntWebDelay", &IntWebDelay);
				InStreams = op_topo_assoc_count(MyID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_STRM);
				OutStreams = op_topo_assoc_count(MyID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_STRM);
				/*Find the Packet and AppData Streams*/
				
				for (index = 0; index < InStreams; index++)
				{
					/*Find the stream index at the specific association*/
					StrmID = op_topo_assoc(MyID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_STRM, index);
					
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_QUEUE)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_QUEUE,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "USER") == 0)
							{
								op_ima_obj_attr_get(StrmID, "dest stream", &UserINStream);
								printf("UserINStream: %d\n",UserINStream);
							}
					}
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_PTRX)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_PTRX,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "RX_SERV_WEB") == 0)
							{
								op_ima_obj_attr_get(StrmID, "dest stream", &RXservWEBStream);
								printf("SERV RXservWEBStream: %d\n",RXservWEBStream);
							}
					}
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_PTRX)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_PTRX,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "RX_SERV_UTP") == 0)
							{
								op_ima_obj_attr_get(StrmID, "dest stream", &RXservUTPStream);
								printf("SERV RXservUTPStream: %d\n",RXservUTPStream);
							}
					}
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_PTRX)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_PTRX,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "RX_SERV_TCP") == 0)
							{
								op_ima_obj_attr_get(StrmID, "dest stream", &RXservTCPStream);
								printf("SERV RXservTCPStream: %d\n",RXservTCPStream);
							}
					}
				}
				
				for (index = 0; index < OutStreams; index++)
				{
					/*Find the stream index at the specific association*/
					StrmID = op_topo_assoc(MyID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_STRM, index);
					
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_QUEUE)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_QUEUE,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "USER") == 0)
							{
								op_ima_obj_attr_get(StrmID, "src stream", &UserOUTStream);
								printf("UserOUTStream: %d\n",UserOUTStream);
							}
					}
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PTTX)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PTTX,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "TX_SERV_WEB") == 0)
							{
								op_ima_obj_attr_get(StrmID, "src stream", &TXservWEBStream);
								printf("SERV TXservWEBStream: %d\n",TXservWEBStream);
							}
					}
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PTTX)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PTTX,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "TX_SERV_UTP") == 0)
							{
								op_ima_obj_attr_get(StrmID, "src stream", &TXservUTPStream);
								printf("SERV TXservUTPStream: %d\n",TXservUTPStream);
							}
					}
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PTTX)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PTTX,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "TX_SERV_TCP") == 0)
							{
								op_ima_obj_attr_get(StrmID, "src stream", &TXservTCPStream);
								printf("SERV TXservTCPStream: %d\n",TXservTCPStream);
							}
					}
				}
				
				}
				FSM_PROFILE_SECTION_OUT (state0_enter_exec)

			/** state (INIT) exit executives **/
			FSM_STATE_EXIT_FORCED (0, "INIT", "pm_utp_internet_process [INIT exit execs]")


			/** state (INIT) transition processing **/
			FSM_TRANSIT_ONLY ((PowerUp), 1, state1_enter_exec, ;, INIT, "PowerUp", "", "INIT", "IDLE", "tr_0", "pm_utp_internet_process [INIT -> IDLE : PowerUp / ]")
				/*---------------------------------------------------------*/



			/** state (IDLE) enter executives **/
			FSM_STATE_ENTER_UNFORCED (1, "IDLE", state1_enter_exec, "pm_utp_internet_process [IDLE enter execs]")
				FSM_PROFILE_SECTION_IN ("pm_utp_internet_process [IDLE enter execs]", state1_enter_exec)
				{
				
				}
				FSM_PROFILE_SECTION_OUT (state1_enter_exec)

			/** blocking after enter executives of unforced state. **/
			FSM_EXIT (3,"pm_utp_internet_process")


			/** state (IDLE) exit executives **/
			FSM_STATE_EXIT_UNFORCED (1, "IDLE", "pm_utp_internet_process [IDLE exit execs]")
				FSM_PROFILE_SECTION_IN ("pm_utp_internet_process [IDLE exit execs]", state1_exit_exec)
				{
				//printf("\n Packet arrival");
				}
				FSM_PROFILE_SECTION_OUT (state1_exit_exec)


			/** state (IDLE) transition processing **/
			FSM_TRANSIT_ONLY ((PacketArrival), 2, state2_enter_exec, ;, IDLE, "PacketArrival", "", "IDLE", "PKT_HND", "tr_10", "pm_utp_internet_process [IDLE -> PKT_HND : PacketArrival / ]")
				/*---------------------------------------------------------*/



			/** state (PKT_HND) enter executives **/
			FSM_STATE_ENTER_FORCED (2, "PKT_HND", state2_enter_exec, "pm_utp_internet_process [PKT_HND enter execs]")
				FSM_PROFILE_SECTION_IN ("pm_utp_internet_process [PKT_HND enter execs]", state2_enter_exec)
				{
				Packet* ip_packet;
				int type,BUFF_TYPE;
				double internet_delay;
				/*DOWNLINK, so PASS to the network*/
				if(jitter_mode==0)
					internet_delay=IntDelay;
				else if(jitter_mode==1)
					{
					internet_delay=IntDelay+op_dist_exponential(0.005)-0.005;
					
					}
				
				if(op_intrpt_strm () == UserINStream)
					{
					//printf("\n IN UserINStream");
					/* Obtain the incoming packet.	*/
					ip_packet = op_pk_get (UserINStream);
					//printf("\n IN UserINStream, BUFF: %f, size: %d, timestamp:%f", op_subq_stat (BuffUL, OPC_QSTAT_PKSIZE),op_pk_total_size_get(ip_packet)/8,op_sim_time());
					op_pk_nfd_access (ip_packet, "type",&type);
					BUFF_TYPE=(int)BuffUL;
					if(type==TCP_DATA)
						{
						op_pk_nfd_set (ip_packet, "dst",TXservTCPStream);
						}
					else if(type==UTP_DATA)
						{
						op_pk_nfd_set (ip_packet, "dst",TXservUTPStream);
						}
					else if(type==WEB_DATA)
						{
						op_pk_nfd_set (ip_packet, "dst",TXservWEBStream);
						
						internet_delay=IntWebDelay;
						
						BUFF_TYPE=(int)BuffULWEB;
						}
					
					if(op_subq_stat (BUFF_TYPE, OPC_QSTAT_FREE_PKSIZE)==0)
						{
						op_pk_destroy (ip_packet);
						printf("\n RXStream packet Destroyed");
						}
					else if(op_subq_pk_insert(BUFF_TYPE, ip_packet, OPC_QPOS_TAIL)!= OPC_QINS_OK)
						printf("\n Packet not queued");
					else if(op_subq_stat (BUFF_TYPE, OPC_QSTAT_PKSIZE)>0)
						{
						op_intrpt_schedule_self(op_sim_time() + internet_delay, BUFF_TYPE);
						//printf("\n SERV RXStream packet starts transmission");
						}
					
					
					}
				else 
					{
					//printf("\n SERV RXStream ");
					/* Obtain the incoming packet.	*/
					pkptr = op_pk_get (op_intrpt_strm ());
					ip_packet = op_pk_create_fmt ("pm_ip_packet");
					op_pk_nfd_set (ip_packet, "src",op_intrpt_strm ());
					BUFF_TYPE=(int)BuffDL;
					if(op_intrpt_strm () == RXservUTPStream)
						{
						op_pk_nfd_set (ip_packet, "type",UTP_DATA);
						op_pk_nfd_set (ip_packet, "dst",UTP_DATA);
						}
					else if(op_intrpt_strm () == RXservWEBStream)
						{
						op_pk_nfd_set (ip_packet, "type",WEB_DATA);
						op_pk_nfd_set (ip_packet, "dst",WEB_DATA);
						
						internet_delay=IntWebDelay;
						
						BUFF_TYPE=(int)BuffDLWEB;
						}
					else if(op_intrpt_strm () == RXservTCPStream)
						{
						op_pk_nfd_set (ip_packet, "type",TCP_DATA);	
						op_pk_nfd_set (ip_packet, "dst",TCP_DATA);
						}
					
					op_pk_nfd_set_pkt (ip_packet, "data_field", pkptr);
					
					//printf("\n IN RXservStream, BUFF: %f", op_subq_stat (BuffDL, OPC_QSTAT_PKSIZE));
					if(op_subq_stat (BUFF_TYPE, OPC_QSTAT_FREE_PKSIZE)==0)
						{
						op_pk_destroy (ip_packet);
						printf("\n RXStream packet Destroyed");
						}
					else if(op_subq_pk_insert(BUFF_TYPE, ip_packet, OPC_QPOS_TAIL)!= OPC_QINS_OK)
						printf("\n Packet not queued");
					else if(op_subq_stat (BUFF_TYPE, OPC_QSTAT_PKSIZE)>0)
						{
						op_intrpt_schedule_self(op_sim_time() + internet_delay, BUFF_TYPE);
						}
				
					}
				}
				FSM_PROFILE_SECTION_OUT (state2_enter_exec)

			/** state (PKT_HND) exit executives **/
			FSM_STATE_EXIT_FORCED (2, "PKT_HND", "pm_utp_internet_process [PKT_HND exit execs]")


			/** state (PKT_HND) transition processing **/
			FSM_PROFILE_SECTION_IN ("pm_utp_internet_process [PKT_HND trans conditions]", state2_trans_conds)
			FSM_INIT_COND (NotEmptyQueue)
			FSM_TEST_COND (EmptyQueue)
			FSM_TEST_LOGIC ("PKT_HND")
			FSM_PROFILE_SECTION_OUT (state2_trans_conds)

			FSM_TRANSIT_SWITCH
				{
				FSM_CASE_TRANSIT (0, 3, state3_enter_exec, ;, "NotEmptyQueue", "", "PKT_HND", "WAIT_INRT", "tr_12", "pm_utp_internet_process [PKT_HND -> WAIT_INRT : NotEmptyQueue / ]")
				FSM_CASE_TRANSIT (1, 1, state1_enter_exec, ;, "EmptyQueue", "", "PKT_HND", "IDLE", "tr_13", "pm_utp_internet_process [PKT_HND -> IDLE : EmptyQueue / ]")
				}
				/*---------------------------------------------------------*/



			/** state (WAIT_INRT) enter executives **/
			FSM_STATE_ENTER_UNFORCED (3, "WAIT_INRT", state3_enter_exec, "pm_utp_internet_process [WAIT_INRT enter execs]")
				FSM_PROFILE_SECTION_IN ("pm_utp_internet_process [WAIT_INRT enter execs]", state3_enter_exec)
				{
				//printf("\n In WAIT_TRA");
				}
				FSM_PROFILE_SECTION_OUT (state3_enter_exec)

			/** blocking after enter executives of unforced state. **/
			FSM_EXIT (7,"pm_utp_internet_process")


			/** state (WAIT_INRT) exit executives **/
			FSM_STATE_EXIT_UNFORCED (3, "WAIT_INRT", "pm_utp_internet_process [WAIT_INRT exit execs]")


			/** state (WAIT_INRT) transition processing **/
			FSM_PROFILE_SECTION_IN ("pm_utp_internet_process [WAIT_INRT trans conditions]", state3_trans_conds)
			FSM_INIT_COND (PacketArrival)
			FSM_TEST_COND (TransOver)
			FSM_TEST_LOGIC ("WAIT_INRT")
			FSM_PROFILE_SECTION_OUT (state3_trans_conds)

			FSM_TRANSIT_SWITCH
				{
				FSM_CASE_TRANSIT (0, 2, state2_enter_exec, ;, "PacketArrival", "", "WAIT_INRT", "PKT_HND", "tr_15", "pm_utp_internet_process [WAIT_INRT -> PKT_HND : PacketArrival / ]")
				FSM_CASE_TRANSIT (1, 4, state4_enter_exec, ;, "TransOver", "", "WAIT_INRT", "SEND", "tr_16", "pm_utp_internet_process [WAIT_INRT -> SEND : TransOver / ]")
				}
				/*---------------------------------------------------------*/



			/** state (SEND) enter executives **/
			FSM_STATE_ENTER_FORCED (4, "SEND", state4_enter_exec, "pm_utp_internet_process [SEND enter execs]")
				FSM_PROFILE_SECTION_IN ("pm_utp_internet_process [SEND enter execs]", state4_enter_exec)
				{
				int dst,type;
				Packet* ip_packet;
				/* Send the incoming packet.	*/
				if(op_intrpt_code ()==BuffDL)
					{
					pkptr = op_subq_pk_remove (BuffDL, OPC_QPOS_HEAD);
					op_pk_send (pkptr, UserOUTStream);
					//printf("\n CLOUD UserOUTStream Packet finished transmission");
				
					
					}
				else if(op_intrpt_code ()==BuffDLWEB)
					{
					pkptr = op_subq_pk_remove (BuffDLWEB, OPC_QPOS_HEAD);
					op_pk_send (pkptr, UserOUTStream);
					//printf("\n CLOUD UserOUTStream Packet finished transmission");
				
					
					}
				else if(op_intrpt_code ()==BuffUL)
					{
					ip_packet = op_subq_pk_remove (BuffUL, OPC_QPOS_HEAD);
					op_pk_nfd_access (ip_packet, "type", &type);
					//printf("\n SERV BuffUL, dst: %d Packet finished transmission",dst);
					if(type==TCP_DATA)
						{
						dst=TXservTCPStream;
						}
					else if(type==UTP_DATA)
						{
						dst=TXservUTPStream;
						}
					else if(type==WEB_DATA)
						{
						dst=TXservWEBStream;
						}
					
					//printf("\n SERV BuffUL, dst: %d Packet finished transmission",dst);
					//printf("\n CLOUD TXserv, Packet send to: %d",dst);
					op_pk_nfd_get_pkt (ip_packet, "data_field", &pkptr);
					op_pk_send (pkptr, dst);
					op_pk_destroy (ip_packet);
					}
				else if(op_intrpt_code ()==BuffULWEB)
					{
					ip_packet = op_subq_pk_remove (BuffULWEB, OPC_QPOS_HEAD);
					op_pk_nfd_access (ip_packet, "type", &type);
					//printf("\n SERV BuffUL, dst: %d Packet finished transmission",dst);
					if(type==TCP_DATA)
						{
						dst=TXservTCPStream;
						}
					else if(type==UTP_DATA)
						{
						dst=TXservUTPStream;
						}
					else if(type==WEB_DATA)
						{
						dst=TXservWEBStream;
						}
					
					//printf("\n SERV BuffUL, dst: %d Packet finished transmission",dst);
					//printf("\n CLOUD TXserv, Packet send to: %d",dst);
					op_pk_nfd_get_pkt (ip_packet, "data_field", &pkptr);
					op_pk_send (pkptr, dst);
					op_pk_destroy (ip_packet);
					}
				}
				FSM_PROFILE_SECTION_OUT (state4_enter_exec)

			/** state (SEND) exit executives **/
			FSM_STATE_EXIT_FORCED (4, "SEND", "pm_utp_internet_process [SEND exit execs]")


			/** state (SEND) transition processing **/
			FSM_PROFILE_SECTION_IN ("pm_utp_internet_process [SEND trans conditions]", state4_trans_conds)
			FSM_INIT_COND (EmptyQueue)
			FSM_TEST_COND (NotEmptyQueue)
			FSM_TEST_LOGIC ("SEND")
			FSM_PROFILE_SECTION_OUT (state4_trans_conds)

			FSM_TRANSIT_SWITCH
				{
				FSM_CASE_TRANSIT (0, 1, state1_enter_exec, ;, "EmptyQueue", "", "SEND", "IDLE", "tr_17", "pm_utp_internet_process [SEND -> IDLE : EmptyQueue / ]")
				FSM_CASE_TRANSIT (1, 3, state3_enter_exec, ;, "NotEmptyQueue", "", "SEND", "WAIT_INRT", "tr_18", "pm_utp_internet_process [SEND -> WAIT_INRT : NotEmptyQueue / ]")
				}
				/*---------------------------------------------------------*/



			}


		FSM_EXIT (0,"pm_utp_internet_process")
		}
	}




void
_op_pm_utp_internet_process_diag (OP_SIM_CONTEXT_ARG_OPT)
	{
	/* No Diagnostic Block */
	}




void
_op_pm_utp_internet_process_terminate (OP_SIM_CONTEXT_ARG_OPT)
	{

	FIN_MT (_op_pm_utp_internet_process_terminate ())


	/* No Termination Block */

	Vos_Poolmem_Dealloc (op_sv_ptr);

	FOUT
	}


/* Undefine shortcuts to state variables to avoid */
/* syntax error in direct access to fields of */
/* local variable prs_ptr in _op_pm_utp_internet_process_svar function. */
#undef UserINStream
#undef UserOUTStream
#undef RXservWEBStream
#undef TXservWEBStream
#undef TrFinD
#undef IntDelay
#undef TrFinU
#undef RXservUTPStream
#undef TXservUTPStream
#undef RXservTCPStream
#undef TXservTCPStream
#undef IntWebDelay
#undef jitter_mode

#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE

#define FIN_PREAMBLE_DEC
#define FIN_PREAMBLE_CODE

VosT_Obtype
_op_pm_utp_internet_process_init (int * init_block_ptr)
	{
	VosT_Obtype obtype = OPC_NIL;
	FIN_MT (_op_pm_utp_internet_process_init (init_block_ptr))

	obtype = Vos_Define_Object_Prstate ("proc state vars (pm_utp_internet_process)",
		sizeof (pm_utp_internet_process_state));
	*init_block_ptr = 0;

	FRET (obtype)
	}

VosT_Address
_op_pm_utp_internet_process_alloc (VosT_Obtype obtype, int init_block)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	pm_utp_internet_process_state * ptr;
	FIN_MT (_op_pm_utp_internet_process_alloc (obtype))

	ptr = (pm_utp_internet_process_state *)Vos_Alloc_Object (obtype);
	if (ptr != OPC_NIL)
		{
		ptr->_op_current_block = init_block;
#if defined (OPD_ALLOW_ODB)
		ptr->_op_current_state = "pm_utp_internet_process [INIT enter execs]";
#endif
		}
	FRET ((VosT_Address)ptr)
	}



void
_op_pm_utp_internet_process_svar (void * gen_ptr, const char * var_name, void ** var_p_ptr)
	{
	pm_utp_internet_process_state		*prs_ptr;

	FIN_MT (_op_pm_utp_internet_process_svar (gen_ptr, var_name, var_p_ptr))

	if (var_name == OPC_NIL)
		{
		*var_p_ptr = (void *)OPC_NIL;
		FOUT
		}
	prs_ptr = (pm_utp_internet_process_state *)gen_ptr;

	if (strcmp ("UserINStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->UserINStream);
		FOUT
		}
	if (strcmp ("UserOUTStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->UserOUTStream);
		FOUT
		}
	if (strcmp ("RXservWEBStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->RXservWEBStream);
		FOUT
		}
	if (strcmp ("TXservWEBStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->TXservWEBStream);
		FOUT
		}
	if (strcmp ("TrFinD" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->TrFinD);
		FOUT
		}
	if (strcmp ("IntDelay" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->IntDelay);
		FOUT
		}
	if (strcmp ("TrFinU" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->TrFinU);
		FOUT
		}
	if (strcmp ("RXservUTPStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->RXservUTPStream);
		FOUT
		}
	if (strcmp ("TXservUTPStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->TXservUTPStream);
		FOUT
		}
	if (strcmp ("RXservTCPStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->RXservTCPStream);
		FOUT
		}
	if (strcmp ("TXservTCPStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->TXservTCPStream);
		FOUT
		}
	if (strcmp ("IntWebDelay" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->IntWebDelay);
		FOUT
		}
	if (strcmp ("jitter_mode" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->jitter_mode);
		FOUT
		}
	*var_p_ptr = (void *)OPC_NIL;

	FOUT
	}

