/* Process model C form file: pm_web_process.pr.c */
/* Portions of this file copyright 1986-2012 by OPNET Technologies, Inc. */


/*
 =========================== NOTE ==========================
 This file is automatically generated from pm_web_process.pr.m
 during a process model compilation.

 Do NOT manually edit this file.
 Manual edits will be lost during the next compilation.
 =========================== NOTE ==========================
*/



/* This variable carries the header into the object file */
const char pm_web_process_pr_c [] = "MIL_3_Tfile_Hdr_ 171A 30A op_runsim_dev 7 552BF5D1 552BF5D1 1 FTNK-B0013 s146147 0 0 none none 0 0 none 0 0 0 0 0 0 0 0 2b74 2                                                                                                                                                                                                                                                                                                                                                                                                 ";
#include <string.h>



/* OPNET system definitions */
#include <opnet.h>



/* Header Block */

#define PowerUp (op_intrpt_type() == OPC_INTRPT_BEGSIM) 
#define PacketArrival (op_intrpt_type() == OPC_INTRPT_STRM && op_intrpt_strm()==PckStream) 
#define AppDataArrival (op_intrpt_type() == OPC_INTRPT_STRM && op_intrpt_strm()==AppDataStream)
#define TimerOver (op_intrpt_type() == OPC_INTRPT_SELF) 
#define DataPacketArrival (op_pk_total_size_get(tcp_packet_ptr)!=1)
/* Macro for determining the number of packets in the queue */ 
#define QSize (op_subq_stat(0, OPC_QSTAT_PKSIZE))


/* End of Header Block */

#if !defined (VOSD_NO_FIN)
#undef	BIN
#undef	BOUT
#define	BIN		FIN_LOCAL_FIELD(_op_last_line_passed) = __LINE__ - _op_block_origin;
#define	BOUT	BIN
#define	BINIT	FIN_LOCAL_FIELD(_op_last_line_passed) = 0; _op_block_origin = __LINE__;
#else
#define	BINIT
#endif /* #if !defined (VOSD_NO_FIN) */



/* State variable definitions */
typedef struct
	{
	/* Internal state tracking for FSM */
	FSM_SYS_STATE
	/* State Variables */
	int	                    		PckStream                                       ;
	int	                    		AppDataStream                                   ;
	int	                    		SinkStream                                      ;
	int	                    		TransStream                                     ;
	int	                    		RecNextPckSeq                                   ;
	int	                    		TrNextPckSeq                                    ;
	int	                    		TrWaitAckSeq                                    ;
	Stathandle	             		retr_per_pkt_hndl                               ;
	double	                 		retr_per_pkt                                    ;
	double	                 		TimeOutTimer                                    ;
	Evhandle	               		Timer                                           ;
	Boolean	                		DataPktArr                                      ;
	int	                    		TrPckSeq                                        ;
	Stathandle	             		retr_hndl                                       ;
	double	                 		retr                                            ;
	} pm_web_process_state;

#define PckStream               		op_sv_ptr->PckStream
#define AppDataStream           		op_sv_ptr->AppDataStream
#define SinkStream              		op_sv_ptr->SinkStream
#define TransStream             		op_sv_ptr->TransStream
#define RecNextPckSeq           		op_sv_ptr->RecNextPckSeq
#define TrNextPckSeq            		op_sv_ptr->TrNextPckSeq
#define TrWaitAckSeq            		op_sv_ptr->TrWaitAckSeq
#define retr_per_pkt_hndl       		op_sv_ptr->retr_per_pkt_hndl
#define retr_per_pkt            		op_sv_ptr->retr_per_pkt
#define TimeOutTimer            		op_sv_ptr->TimeOutTimer
#define Timer                   		op_sv_ptr->Timer
#define DataPktArr              		op_sv_ptr->DataPktArr
#define TrPckSeq                		op_sv_ptr->TrPckSeq
#define retr_hndl               		op_sv_ptr->retr_hndl
#define retr                    		op_sv_ptr->retr

/* These macro definitions will define a local variable called	*/
/* "op_sv_ptr" in each function containing a FIN statement.	*/
/* This variable points to the state variable data structure,	*/
/* and can be used from a C debugger to display their values.	*/
#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE
#define FIN_PREAMBLE_DEC	pm_web_process_state *op_sv_ptr;
#define FIN_PREAMBLE_CODE	\
		op_sv_ptr = ((pm_web_process_state *)(OP_SIM_CONTEXT_PTR->_op_mod_state_ptr));


/* No Function Block */

#if !defined (VOSD_NO_FIN)
enum { _op_block_origin = __LINE__ };
#endif

/* Undefine optional tracing in FIN/FOUT/FRET */
/* The FSM has its own tracing code and the other */
/* functions should not have any tracing.		  */
#undef FIN_TRACING
#define FIN_TRACING

#undef FOUTRET_TRACING
#define FOUTRET_TRACING

#if defined (__cplusplus)
extern "C" {
#endif
	void pm_web_process (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Obtype _op_pm_web_process_init (int * init_block_ptr);
	void _op_pm_web_process_diag (OP_SIM_CONTEXT_ARG_OPT);
	void _op_pm_web_process_terminate (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Address _op_pm_web_process_alloc (VosT_Obtype, int);
	void _op_pm_web_process_svar (void *, const char *, void **);


#if defined (__cplusplus)
} /* end of 'extern "C"' */
#endif




/* Process model interrupt handling procedure */


void
pm_web_process (OP_SIM_CONTEXT_ARG_OPT)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	FIN_MT (pm_web_process ());

		{
		/* Temporary Variables */
		int seq;
		double creation_time;
		Packet* pkptr;
		Packet* ackptr;
		Packet* tcp_packet_ptr;
		/* End of Temporary Variables */


		FSM_ENTER ("pm_web_process")

		FSM_BLOCK_SWITCH
			{
			/*---------------------------------------------------------*/
			/** state (INIT) enter executives **/
			FSM_STATE_ENTER_FORCED_NOLABEL (0, "INIT", "pm_web_process [INIT enter execs]")
				FSM_PROFILE_SECTION_IN ("pm_web_process [INIT enter execs]", state0_enter_exec)
				{
				/*ID of the connections Incoming*/
				Objid MyID, StrmID, OtherID;
				int index, InStreams,OutStreams;
				char ModuleName[64];
				MyID = op_id_self();
				
				op_ima_obj_attr_get (MyID, "TimeOutTimer", &TimeOutTimer);
				retr_per_pkt_hndl   = op_stat_reg ("uTP.Retransmissions (1/packets)",		OPC_STAT_INDEX_NONE, OPC_STAT_LOCAL);
				retr_hndl   = op_stat_reg ("uTP.Retransmissions",		OPC_STAT_INDEX_NONE, OPC_STAT_LOCAL);
				InStreams = op_topo_assoc_count(MyID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_STRM);
				OutStreams = op_topo_assoc_count(MyID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_STRM);
				/*Find the Packet and AppData Streams*/
				
				for (index = 0; index < InStreams; index++)
				{
					/*Find the stream index at the specific association*/
					StrmID = op_topo_assoc(MyID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_STRM, index);
					
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_PROC)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_PROC,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "Traffic Source") == 0)
							{
								op_ima_obj_attr_get(StrmID, "dest stream", &AppDataStream);
							}
					}
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_PTRX)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_PTRX,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "RX") == 0)
							{
								op_ima_obj_attr_get(StrmID, "dest stream", &PckStream);
							}
					}
				}
				
				for (index = 0; index < OutStreams; index++)
				{
					/*Find the stream index at the specific association*/
					StrmID = op_topo_assoc(MyID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_STRM, index);
					
					if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PROC)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PROC,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "Traffic Sink") == 0)
							{
								op_ima_obj_attr_get(StrmID, "src stream", &SinkStream);
								printf("SinkStream: %d\n",SinkStream);
							}
					}
					else if(op_topo_assoc_count(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PTTX)!=0)
					{
						/*Find the process index at the specific association*/
						OtherID = op_topo_assoc(StrmID, OPC_TOPO_ASSOC_OUT, OPC_OBJTYPE_PTTX,0);
						/*Access the attribute name and find the proper streams*/
						op_ima_obj_attr_get(OtherID, "name", ModuleName);
						if (strcmp(ModuleName, "TX") == 0)
							{
								op_ima_obj_attr_get(StrmID, "src stream", &TransStream);
								printf("TransStream: %d\n",TransStream);
							}
					}
				}
				
				/*Initialization*/
				RecNextPckSeq=0;
				TrNextPckSeq=0;
				retr_per_pkt=0;
				retr=0;
				}
				FSM_PROFILE_SECTION_OUT (state0_enter_exec)

			/** state (INIT) exit executives **/
			FSM_STATE_EXIT_FORCED (0, "INIT", "pm_web_process [INIT exit execs]")


			/** state (INIT) transition processing **/
			FSM_TRANSIT_ONLY ((PowerUp), 1, state1_enter_exec, ;, INIT, "PowerUp", "", "INIT", "IDLE", "tr_0", "pm_web_process [INIT -> IDLE : PowerUp / ]")
				/*---------------------------------------------------------*/



			/** state (IDLE) enter executives **/
			FSM_STATE_ENTER_UNFORCED (1, "IDLE", state1_enter_exec, "pm_web_process [IDLE enter execs]")

			/** blocking after enter executives of unforced state. **/
			FSM_EXIT (3,"pm_web_process")


			/** state (IDLE) exit executives **/
			FSM_STATE_EXIT_UNFORCED (1, "IDLE", "pm_web_process [IDLE exit execs]")
				FSM_PROFILE_SECTION_IN ("pm_web_process [IDLE exit execs]", state1_exit_exec)
				{
				Packet* pkptr_queue;
				if ((PacketArrival)) 
					{
					tcp_packet_ptr = op_pk_get(PckStream);
					if (DataPacketArrival)
						{
							/*Data packet arrival*/
							DataPktArr=DataPacketArrival;
							op_pk_nfd_get (tcp_packet_ptr, "seq", &seq);
							
							//printf("\n NODE %d IDLE DataPktArr of size=%d, seq=%d, Exp seq=%d", op_topo_parent(op_id_self()),op_pk_total_size_get(tcp_packet_ptr),seq,RecNextPckSeq);
							if(seq==RecNextPckSeq)
								{
								op_pk_nfd_get_pkt (tcp_packet_ptr, "data_field", &pkptr);
								op_pk_send(pkptr, SinkStream);
								if(RecNextPckSeq==0)
									RecNextPckSeq=1;
								else
									RecNextPckSeq=0;
								
								}
							else
								op_pk_destroy (tcp_packet_ptr);
								
							ackptr = op_pk_create_fmt ("pm_tcp_ack_packet");
							op_pk_nfd_set (ackptr, "seq", RecNextPckSeq);
							op_pk_send(ackptr, TransStream);
						}
					else 
						{
							/*ACK packet arrival*/
							op_pk_nfd_get (tcp_packet_ptr, "seq", &seq);
							//printf("\n NODE %d IDLE AckArr - LOGICAL ERROR! of size=%d seq=%d",op_topo_parent(op_id_self()),op_pk_total_size_get (tcp_packet_ptr), seq);
							
						}
					
					}
				else if ((AppDataArrival)) 
					{
					
					pkptr = op_pk_get(AppDataStream);
					/*Copy pkt and queue it, original one send*/
					creation_time=op_pk_creation_time_get (pkptr);
					pkptr_queue=op_pk_copy(pkptr);
					if(op_subq_pk_insert(0, pkptr_queue, OPC_QPOS_TAIL)!= OPC_QINS_OK)
						printf("\n Packet not queued");
					
					/*Encapsulate, Transmit and wait for ack*/
					TrPckSeq=TrNextPckSeq;
					if(TrNextPckSeq==0)
						TrWaitAckSeq=1;
					else
						TrWaitAckSeq=0;
					//printf("\n NODE %d IDLE AppDataArr seq=%d ", op_topo_parent(op_id_self()),TrNextPckSeq);
					tcp_packet_ptr = op_pk_create_fmt ("pm_tcp_packet");
					op_pk_nfd_set_pkt (tcp_packet_ptr, "data_field", pkptr);
					op_pk_nfd_set (tcp_packet_ptr, "seq",TrPckSeq);
					op_pk_send(tcp_packet_ptr, TransStream);
					printf("\n NODE %d IDLE Send pkt of seq=%d, size=%d",op_topo_parent(op_id_self()),TrPckSeq,op_pk_total_size_get (tcp_packet_ptr));
					Timer=op_intrpt_schedule_self(op_sim_time() + TimeOutTimer, 0);
					}
				}
				FSM_PROFILE_SECTION_OUT (state1_exit_exec)


			/** state (IDLE) transition processing **/
			FSM_PROFILE_SECTION_IN ("pm_web_process [IDLE trans conditions]", state1_trans_conds)
			FSM_INIT_COND (AppDataArrival)
			FSM_TEST_COND (PacketArrival)
			FSM_TEST_LOGIC ("IDLE")
			FSM_PROFILE_SECTION_OUT (state1_trans_conds)

			FSM_TRANSIT_SWITCH
				{
				FSM_CASE_TRANSIT (0, 2, state2_enter_exec, ;, "AppDataArrival", "", "IDLE", "WAIT_ACK", "tr_4", "pm_web_process [IDLE -> WAIT_ACK : AppDataArrival / ]")
				FSM_CASE_TRANSIT (1, 1, state1_enter_exec, ;, "PacketArrival", "", "IDLE", "IDLE", "tr_5", "pm_web_process [IDLE -> IDLE : PacketArrival / ]")
				}
				/*---------------------------------------------------------*/



			/** state (WAIT_ACK) enter executives **/
			FSM_STATE_ENTER_UNFORCED (2, "WAIT_ACK", state2_enter_exec, "pm_web_process [WAIT_ACK enter execs]")

			/** blocking after enter executives of unforced state. **/
			FSM_EXIT (5,"pm_web_process")


			/** state (WAIT_ACK) exit executives **/
			FSM_STATE_EXIT_UNFORCED (2, "WAIT_ACK", "pm_web_process [WAIT_ACK exit execs]")
				FSM_PROFILE_SECTION_IN ("pm_web_process [WAIT_ACK exit execs]", state2_exit_exec)
				{
				if (PacketArrival) 
					{
					tcp_packet_ptr = op_pk_get(PckStream);
					if (DataPacketArrival)
						{
							/*Data packet arrival*/
							DataPktArr=DataPacketArrival;
							op_pk_nfd_get (tcp_packet_ptr, "seq", &seq);
							//printf("\n NODE %d WAITACK DataPktArr of size=%d, seq=%d, Exp seq=%d", op_topo_parent(op_id_self()),op_pk_total_size_get(tcp_packet_ptr),seq,RecNextPckSeq);
							if(seq==RecNextPckSeq)
								{
								op_pk_nfd_get_pkt (tcp_packet_ptr, "data_field", &pkptr);
								op_pk_send(pkptr, SinkStream);
								if(RecNextPckSeq==0)
									RecNextPckSeq=1;
								else
									RecNextPckSeq=0;
								}
							else
								op_pk_destroy (tcp_packet_ptr);
							
							ackptr = op_pk_create_fmt ("pm_tcp_ack_packet");
							op_pk_nfd_set (ackptr, "seq", RecNextPckSeq);
							op_pk_send(ackptr, TransStream);
						}
					else 
						{
							/*ACK packet arrival*/
							DataPktArr=DataPacketArrival;
							op_ev_cancel(Timer);
							op_pk_nfd_get (tcp_packet_ptr, "seq", &seq);
							
							/*ACK is proper*/
							if(seq==TrWaitAckSeq)
								{
								//printf("\n NODE %d WAITACK AckArr of size=%d seq=%d, Exp seq=%d",op_topo_parent(op_id_self()),op_pk_total_size_get (tcp_packet_ptr), seq,TrWaitAckSeq);
								/*Upade the statistics*/
								op_stat_write (retr_per_pkt_hndl,retr_per_pkt);
								op_stat_write (retr_hndl,retr=retr+retr_per_pkt);
								retr_per_pkt=0;
								
								/*Removing copy of the acknowledged packet from the proper queue and destroying*/
								pkptr = op_subq_pk_remove (0, OPC_QPOS_HEAD);
								op_pk_destroy (pkptr);
								
								/*Update seq number for next packet deployed*/
								TrNextPckSeq=TrWaitAckSeq;
								if(QSize>0)
									{
									
									pkptr = op_subq_pk_access (0, OPC_QPOS_HEAD);
									/*Send packet with should be send and update seq of transmited packet*/
									creation_time=op_pk_creation_time_get (pkptr);
									pkptr=op_pk_copy(pkptr);
									op_pk_creation_time_set (pkptr,creation_time);
									TrPckSeq=TrNextPckSeq;
									if(TrNextPckSeq==0)
										TrWaitAckSeq=1;
									else
										TrWaitAckSeq=0;
									tcp_packet_ptr = op_pk_create_fmt ("pm_tcp_packet");
									op_pk_nfd_set_pkt (tcp_packet_ptr, "data_field", pkptr);
									op_pk_nfd_set (tcp_packet_ptr, "seq",TrPckSeq);
									op_pk_send(tcp_packet_ptr, TransStream);
									Timer=op_intrpt_schedule_self(op_sim_time() + TimeOutTimer, 0);
									//printf("\n NODE %d WAITACK Send pkt of seq=%d, size=%d, TrWaitAckSeq=%d, TrNextPckSeq=%d",op_topo_parent(op_id_self()),seq,op_pk_total_size_get (tcp_packet_ptr),TrWaitAckSeq,TrNextPckSeq);
								
									}
								
								
								}
							/*ACK is not proper*/
							else
								{
								/*Retransmit packet*/
								//printf("\n NODE %d WAITACK AckArr of size=%d seq=%d, Exp seq=%d",op_topo_parent(op_id_self()),op_pk_total_size_get (tcp_packet_ptr), seq,TrWaitAckSeq);
								pkptr = op_subq_pk_access (0, OPC_QPOS_HEAD);
								creation_time=op_pk_creation_time_get (pkptr);
								pkptr=op_pk_copy(pkptr);
								op_pk_creation_time_set (pkptr,creation_time);
								tcp_packet_ptr = op_pk_create_fmt ("pm_tcp_packet");
								op_pk_nfd_set_pkt (tcp_packet_ptr, "data_field", pkptr);
								op_pk_nfd_set (tcp_packet_ptr, "seq",TrPckSeq);
								op_pk_send(tcp_packet_ptr, TransStream);
								Timer=op_intrpt_schedule_self(op_sim_time() + TimeOutTimer, 0);
								
								/*Upade the record for retrans. statistics*/
								retr_per_pkt++;
								}
							
							
						}
					
					}
				else if(AppDataArrival) 
					{
					pkptr = op_pk_get(AppDataStream);
					printf("\n NODE %d WAITACK AppDataArrival size=%d", op_topo_parent(op_id_self()),op_pk_total_size_get (pkptr));
				
					if(op_subq_pk_insert (0, pkptr, OPC_QPOS_TAIL) != OPC_QINS_OK)
								printf("\n Packet not queued");
					
					}
				else if(TimerOver) 
					{
					/*Retransmit packet*/
					pkptr = op_subq_pk_access (0, OPC_QPOS_HEAD);
					creation_time=op_pk_creation_time_get (pkptr);
					pkptr=op_pk_copy(pkptr);
					op_pk_creation_time_set (pkptr,creation_time);
					tcp_packet_ptr = op_pk_create_fmt ("pm_tcp_packet");
					op_pk_nfd_set_pkt (tcp_packet_ptr, "data_field", pkptr);
					op_pk_nfd_set (tcp_packet_ptr, "seq",TrPckSeq);
					op_pk_send(tcp_packet_ptr, TransStream);
					Timer=op_intrpt_schedule_self(op_sim_time() + TimeOutTimer, 0);
								
					/*Upade the record for retrans. statistics*/
					retr_per_pkt++;
					//printf("\n NODE %d WAITACK TimeoutArr, retr num=%d of seq=%d", op_topo_parent(op_id_self()),retr_per_pkt,TrNextPckSeq);
					}
				}
				FSM_PROFILE_SECTION_OUT (state2_exit_exec)


			/** state (WAIT_ACK) transition processing **/
			FSM_PROFILE_SECTION_IN ("pm_web_process [WAIT_ACK trans conditions]", state2_trans_conds)
			FSM_INIT_COND (PacketArrival && (QSize>0) && !DataPktArr)
			FSM_TEST_COND (!DataPktArr && PacketArrival && (QSize==0))
			FSM_TEST_COND (AppDataArrival || TimerOver || (PacketArrival && DataPktArr))
			FSM_TEST_LOGIC ("WAIT_ACK")
			FSM_PROFILE_SECTION_OUT (state2_trans_conds)

			FSM_TRANSIT_SWITCH
				{
				FSM_CASE_TRANSIT (0, 2, state2_enter_exec, ;, "PacketArrival && (QSize>0) && !DataPktArr", "", "WAIT_ACK", "WAIT_ACK", "tr_6", "pm_web_process [WAIT_ACK -> WAIT_ACK : PacketArrival && (QSize>0) && !DataPktArr / ]")
				FSM_CASE_TRANSIT (1, 1, state1_enter_exec, ;, "!DataPktArr && PacketArrival && (QSize==0)", "", "WAIT_ACK", "IDLE", "tr_8", "pm_web_process [WAIT_ACK -> IDLE : !DataPktArr && PacketArrival && (QSize==0) / ]")
				FSM_CASE_TRANSIT (2, 2, state2_enter_exec, ;, "AppDataArrival || TimerOver || (PacketArrival && DataPktArr)", "", "WAIT_ACK", "WAIT_ACK", "tr_9", "pm_web_process [WAIT_ACK -> WAIT_ACK : AppDataArrival || TimerOver || (PacketArrival && DataPktArr) / ]")
				}
				/*---------------------------------------------------------*/



			}


		FSM_EXIT (0,"pm_web_process")
		}
	}




void
_op_pm_web_process_diag (OP_SIM_CONTEXT_ARG_OPT)
	{
	/* No Diagnostic Block */
	}




void
_op_pm_web_process_terminate (OP_SIM_CONTEXT_ARG_OPT)
	{

	FIN_MT (_op_pm_web_process_terminate ())


	/* No Termination Block */

	Vos_Poolmem_Dealloc (op_sv_ptr);

	FOUT
	}


/* Undefine shortcuts to state variables to avoid */
/* syntax error in direct access to fields of */
/* local variable prs_ptr in _op_pm_web_process_svar function. */
#undef PckStream
#undef AppDataStream
#undef SinkStream
#undef TransStream
#undef RecNextPckSeq
#undef TrNextPckSeq
#undef TrWaitAckSeq
#undef retr_per_pkt_hndl
#undef retr_per_pkt
#undef TimeOutTimer
#undef Timer
#undef DataPktArr
#undef TrPckSeq
#undef retr_hndl
#undef retr

#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE

#define FIN_PREAMBLE_DEC
#define FIN_PREAMBLE_CODE

VosT_Obtype
_op_pm_web_process_init (int * init_block_ptr)
	{
	VosT_Obtype obtype = OPC_NIL;
	FIN_MT (_op_pm_web_process_init (init_block_ptr))

	obtype = Vos_Define_Object_Prstate ("proc state vars (pm_web_process)",
		sizeof (pm_web_process_state));
	*init_block_ptr = 0;

	FRET (obtype)
	}

VosT_Address
_op_pm_web_process_alloc (VosT_Obtype obtype, int init_block)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	pm_web_process_state * ptr;
	FIN_MT (_op_pm_web_process_alloc (obtype))

	ptr = (pm_web_process_state *)Vos_Alloc_Object (obtype);
	if (ptr != OPC_NIL)
		{
		ptr->_op_current_block = init_block;
#if defined (OPD_ALLOW_ODB)
		ptr->_op_current_state = "pm_web_process [INIT enter execs]";
#endif
		}
	FRET ((VosT_Address)ptr)
	}



void
_op_pm_web_process_svar (void * gen_ptr, const char * var_name, void ** var_p_ptr)
	{
	pm_web_process_state		*prs_ptr;

	FIN_MT (_op_pm_web_process_svar (gen_ptr, var_name, var_p_ptr))

	if (var_name == OPC_NIL)
		{
		*var_p_ptr = (void *)OPC_NIL;
		FOUT
		}
	prs_ptr = (pm_web_process_state *)gen_ptr;

	if (strcmp ("PckStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->PckStream);
		FOUT
		}
	if (strcmp ("AppDataStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->AppDataStream);
		FOUT
		}
	if (strcmp ("SinkStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->SinkStream);
		FOUT
		}
	if (strcmp ("TransStream" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->TransStream);
		FOUT
		}
	if (strcmp ("RecNextPckSeq" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->RecNextPckSeq);
		FOUT
		}
	if (strcmp ("TrNextPckSeq" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->TrNextPckSeq);
		FOUT
		}
	if (strcmp ("TrWaitAckSeq" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->TrWaitAckSeq);
		FOUT
		}
	if (strcmp ("retr_per_pkt_hndl" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->retr_per_pkt_hndl);
		FOUT
		}
	if (strcmp ("retr_per_pkt" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->retr_per_pkt);
		FOUT
		}
	if (strcmp ("TimeOutTimer" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->TimeOutTimer);
		FOUT
		}
	if (strcmp ("Timer" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->Timer);
		FOUT
		}
	if (strcmp ("DataPktArr" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->DataPktArr);
		FOUT
		}
	if (strcmp ("TrPckSeq" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->TrPckSeq);
		FOUT
		}
	if (strcmp ("retr_hndl" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->retr_hndl);
		FOUT
		}
	if (strcmp ("retr" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->retr);
		FOUT
		}
	*var_p_ptr = (void *)OPC_NIL;

	FOUT
	}

